---
title: "Cleaning"
output: html_document
date: '2022-07-24'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T, fig.width=8, fig.height=4)
options(scipen = 0, digits = 3)  # controls base R output
if(!require('pacman')) {
  install.packages('pacman')
}
pacman::p_load(ggplot2, dplyr, tidyverse, gridExtra, ggrepel, plotly, skimr, tidytext) 
# install a package if it does not exist already and put the package in the path (library)
# dplyr, ggplot2,tidyr
```
 
# Cleaning

```{r read}
data2017.2018 <- read.csv("data/2017-2018 - Sheet1.csv")
data2018.2019 <- read.csv("data/2018-2019 - Sheet1.csv")
data2019.2020 <- read.csv("data/2019-2020 - Sheet1.csv")
data2020.2021 <- read.csv("data/2020-2021 - Sheet1.csv")
data2021.2022 <- read.csv("data/2021-2022 - Sheet1.csv")
```

```{r read}
data2017.2018 <- data.frame(year = rep("2017", 20), data2017.2018)
data2018.2019 <- data.frame(year = rep("2018", 20), data2018.2019)
data2019.2020 <- data.frame(year = rep("2019", 20), data2019.2020)
data2020.2021 <- data.frame(year = rep("2020", 20), data2020.2021)
data2021.2022 <- data.frame(year = rep("2021", 20), data2021.2022)
```

```{r combine}
bigdata <- merge(data2017.2018, data2018.2019, all = TRUE)
bigdata <- merge(bigdata, data2019.2020, all = TRUE)
bigdata <- merge(bigdata, data2020.2021, all = TRUE)
bigdata <- merge(bigdata, data2021.2022, all = TRUE)
```

```{r sort}
bigdata <- bigdata[order(bigdata$Squad),]
```

```{r graphs}
sct_plot1 <- bigdata %>%
  ggplot(aes(x = Age, y = Pts)) + 
  # geometric options: color, size, shape, alpha: transparency (range: 0 to 1)
  geom_point(color = "blue", size= 3, alpha = .8) + 
  geom_text_repel(aes(label = Squad), size = 3) +
  labs(title = "Premier League Team's Age vs Pts", 
       x = "Age", 
       y = "Point")
sct_plot1

sct_plot2 <- bigdata %>%
  ggplot(aes(x = CrdY, y = Pts)) + 
  # geometric options: color, size, shape, alpha: transparency (range: 0 to 1)
  geom_point(color = "blue", size= 3, alpha = .8) + 
  geom_text_repel(aes(label = Squad), size = 3) +
  labs(title = "Premier League Team's Yellow Cards vs Pts", 
       x = "Yellow Cards", 
       y = "Point")
sct_plot2

sct_plot3 <- bigdata %>%
  ggplot(aes(x = CrdR, y = Pts)) + 
  # geometric options: color, size, shape, alpha: transparency (range: 0 to 1)
  geom_point(color = "blue", size= 3, alpha = .8) + 
  geom_text_repel(aes(label = Squad), size = 3) +
  labs(title = "Premier League Team's Red Cards vs Pts", 
       x = "Red Cards", 
       y = "Point")
sct_plot3

sct_plot4 <- bigdata %>%
  ggplot(aes(x = Save., y = Pts)) + 
  # geometric options: color, size, shape, alpha: transparency (range: 0 to 1)
  geom_point(color = "blue", size= 3, alpha = .8) + 
  geom_text_repel(aes(label = Squad), size = 3) +
  labs(title = "Premier League Team's Save Percentage vs Pts", 
       x = "Save Percentage", 
       y = "Point")
sct_plot4

sct_plot5 <- bigdata %>%
  ggplot(aes(x = X..Pl, y = Pts)) + 
  # geometric options: color, size, shape, alpha: transparency (range: 0 to 1)
  geom_point(color = "blue", size= 3, alpha = .8) + 
  geom_text_repel(aes(label = Squad), size = 3) +
  labs(title = "Premier League Team's Players Used vs Pts", 
       x = "Players Used", 
       y = "Point")
sct_plot5

```


``` {r adfs}
```
